# Generated by Django 3.2.2 on 2021-05-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estanteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=3)),
                ('pintura', models.CharField(max_length=10)),
                ('estatura', models.CharField(max_length=4)),
            ],
        ),
    ]
