# Generated by Django 3.2.2 on 2021-05-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_caja_locker_mueble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
