# Generated by Django 3.2.2 on 2021-05-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_caja_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estanteria',
            name='peso',
            field=models.CharField(max_length=10),
        ),
    ]
