# Generated by Django 3.2.2 on 2021-05-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_estanteria_estatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caja',
            old_name='material',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='estanteria',
            old_name='nombre',
            new_name='venta',
        ),
        migrations.RenameField(
            model_name='locker',
            old_name='nombre',
            new_name='venta',
        ),
        migrations.RenameField(
            model_name='mueble',
            old_name='nombre',
            new_name='venta',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='tipo',
        ),
        migrations.AddField(
            model_name='caja',
            name='venta',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caja',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
