# Generated by Django 3.2.2 on 2021-05-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210513_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mueble',
            old_name='dimensiones',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='mueble',
            name='precio',
        ),
        migrations.AddField(
            model_name='mueble',
            name='nombre',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mueble',
            name='color',
            field=models.CharField(max_length=20),
        ),
    ]
